set CLK_PERIOD 0.5
set INPUT_SIZE 16
set DATAFLOW_TYPE ws
set ARRAY_TYPE syst2d
set LAT 2
set LAYER 2
set parameters {{N_FILTER 64} {N_CHANNEL 32} {STRIDE 2} {X_SIZE 7} {FILTER_WIDTH 3} {CONVS_PER_LINE 3} {MEM_SIZE 16} {INPUT_SIZE 16} {CARRY_SIZE 4} {SHIFT 8}}
