onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/dut/control/clk
add wave -noupdate /tb/dut/control/reset
add wave -noupdate /tb/dut/control/p_start
add wave -noupdate /tb/dut/control/p_conv_end
add wave -noupdate /tb/dut/control/p_read_valid
add wave -noupdate {/tb/dut/control/\p_output[0] }
add wave -noupdate {/tb/dut/control/\p_output[1] }
add wave -noupdate {/tb/dut/control/\p_output[2] }
add wave -noupdate {/tb/dut/control/\p_output[3] }
add wave -noupdate {/tb/dut/control/\p_output[4] }
add wave -noupdate {/tb/dut/control/\p_output[5] }
add wave -noupdate {/tb/dut/control/\p_output[6] }
add wave -noupdate {/tb/dut/control/\p_output[7] }
add wave -noupdate {/tb/dut/control/\p_output[8] }
add wave -noupdate /tb/dut/control/p_read_data
add wave -noupdate /tb/dut/control/p_end
add wave -noupdate /tb/dut/control/p_conv_start
add wave -noupdate /tb/dut/control/p_read_en
add wave -noupdate /tb/dut/control/p_write_en
add wave -noupdate {/tb/dut/control/\p_input[0] }
add wave -noupdate {/tb/dut/control/\p_input[1] }
add wave -noupdate {/tb/dut/control/\p_input[2] }
add wave -noupdate {/tb/dut/control/\p_input[3] }
add wave -noupdate {/tb/dut/control/\p_input[4] }
add wave -noupdate {/tb/dut/control/\p_input[5] }
add wave -noupdate {/tb/dut/control/\p_input[6] }
add wave -noupdate {/tb/dut/control/\p_input[7] }
add wave -noupdate {/tb/dut/control/\p_input[8] }
add wave -noupdate {/tb/dut/control/\p_input[9] }
add wave -noupdate {/tb/dut/control/\p_input[10] }
add wave -noupdate {/tb/dut/control/\p_input[11] }
add wave -noupdate {/tb/dut/control/\p_input[12] }
add wave -noupdate {/tb/dut/control/\p_input[13] }
add wave -noupdate {/tb/dut/control/\p_input[14] }
add wave -noupdate {/tb/dut/control/\p_input[15] }
add wave -noupdate {/tb/dut/control/\p_input[16] }
add wave -noupdate {/tb/dut/control/\p_input[17] }
add wave -noupdate {/tb/dut/control/\p_input[18] }
add wave -noupdate {/tb/dut/control/\p_input[19] }
add wave -noupdate {/tb/dut/control/\p_input[20] }
add wave -noupdate {/tb/dut/control/\p_input[21] }
add wave -noupdate {/tb/dut/control/\p_input[22] }
add wave -noupdate {/tb/dut/control/\p_input[23] }
add wave -noupdate {/tb/dut/control/\p_input[24] }
add wave -noupdate {/tb/dut/control/\p_weight[0] }
add wave -noupdate {/tb/dut/control/\p_weight[1] }
add wave -noupdate {/tb/dut/control/\p_weight[2] }
add wave -noupdate {/tb/dut/control/\p_weight[3] }
add wave -noupdate {/tb/dut/control/\p_weight[4] }
add wave -noupdate {/tb/dut/control/\p_weight[5] }
add wave -noupdate {/tb/dut/control/\p_weight[6] }
add wave -noupdate {/tb/dut/control/\p_weight[7] }
add wave -noupdate {/tb/dut/control/\p_weight[8] }
add wave -noupdate {/tb/dut/control/\p_weight[9] }
add wave -noupdate {/tb/dut/control/\p_weight[10] }
add wave -noupdate {/tb/dut/control/\p_weight[11] }
add wave -noupdate {/tb/dut/control/\p_weight[12] }
add wave -noupdate {/tb/dut/control/\p_weight[13] }
add wave -noupdate {/tb/dut/control/\p_weight[14] }
add wave -noupdate {/tb/dut/control/\p_weight[15] }
add wave -noupdate {/tb/dut/control/\p_weight[16] }
add wave -noupdate {/tb/dut/control/\p_weight[17] }
add wave -noupdate {/tb/dut/control/\p_weight[18] }
add wave -noupdate {/tb/dut/control/\p_weight[19] }
add wave -noupdate {/tb/dut/control/\p_weight[20] }
add wave -noupdate {/tb/dut/control/\p_weight[21] }
add wave -noupdate {/tb/dut/control/\p_weight[22] }
add wave -noupdate {/tb/dut/control/\p_weight[23] }
add wave -noupdate {/tb/dut/control/\p_weight[24] }
add wave -noupdate {/tb/dut/control/\p_weight[25] }
add wave -noupdate {/tb/dut/control/\p_weight[26] }
add wave -noupdate {/tb/dut/control/\p_weight[27] }
add wave -noupdate {/tb/dut/control/\p_weight[28] }
add wave -noupdate {/tb/dut/control/\p_weight[29] }
add wave -noupdate {/tb/dut/control/\p_weight[30] }
add wave -noupdate {/tb/dut/control/\p_weight[31] }
add wave -noupdate {/tb/dut/control/\p_weight[32] }
add wave -noupdate {/tb/dut/control/\p_weight[33] }
add wave -noupdate {/tb/dut/control/\p_weight[34] }
add wave -noupdate {/tb/dut/control/\p_weight[35] }
add wave -noupdate /tb/dut/control/p_write_data
add wave -noupdate /tb/dut/control/p_read_addr
add wave -noupdate /tb/dut/control/p_write_addr
add wave -noupdate {/tb/dut/control/\r_feat_out[0] }
add wave -noupdate {/tb/dut/control/\r_feat_out[1] }
add wave -noupdate {/tb/dut/control/\r_feat_out[2] }
add wave -noupdate {/tb/dut/control/\r_feat_out[3] }
add wave -noupdate {/tb/dut/control/\r_feat_out[4] }
add wave -noupdate {/tb/dut/control/\r_feat_out[5] }
add wave -noupdate {/tb/dut/control/\r_feat_out[6] }
add wave -noupdate {/tb/dut/control/\r_feat_out[7] }
add wave -noupdate {/tb/dut/control/\r_feat_out[8] }
add wave -noupdate /tb/dut/control/r_addr_fin
add wave -noupdate /tb/dut/control/r_addr_wh
add wave -noupdate /tb/dut/control/r_addr_fout
add wave -noupdate /tb/dut/control/r_count_fin
add wave -noupdate /tb/dut/control/r_count_fout
add wave -noupdate /tb/dut/control/r_count_wh
add wave -noupdate /tb/dut/control/r_count_fin_horizontal
add wave -noupdate /tb/dut/control/r_addr_bias
add wave -noupdate /tb/dut/control/current_st_input
add wave -noupdate /tb/dut/control/r_count_fout_horizontal
add wave -noupdate /tb/dut/control/r_count_window
add wave -noupdate /tb/dut/control/UNCONNECTED
add wave -noupdate /tb/dut/control/UNCONNECTED0
add wave -noupdate /tb/dut/control/UNCONNECTED1
add wave -noupdate /tb/dut/control/UNCONNECTED2
add wave -noupdate /tb/dut/control/UNCONNECTED3
add wave -noupdate /tb/dut/control/UNCONNECTED4
add wave -noupdate /tb/dut/control/UNCONNECTED5
add wave -noupdate /tb/dut/control/UNCONNECTED6
add wave -noupdate /tb/dut/control/UNCONNECTED7
add wave -noupdate /tb/dut/control/UNCONNECTED8
add wave -noupdate /tb/dut/control/UNCONNECTED9
add wave -noupdate /tb/dut/control/UNCONNECTED10
add wave -noupdate /tb/dut/control/UNCONNECTED11
add wave -noupdate /tb/dut/control/UNCONNECTED12
add wave -noupdate /tb/dut/control/UNCONNECTED13
add wave -noupdate /tb/dut/control/UNCONNECTED14
add wave -noupdate /tb/dut/control/UNCONNECTED15
add wave -noupdate /tb/dut/control/UNCONNECTED16
add wave -noupdate /tb/dut/control/UNCONNECTED17
add wave -noupdate /tb/dut/control/UNCONNECTED18
add wave -noupdate /tb/dut/control/UNCONNECTED19
add wave -noupdate /tb/dut/control/UNCONNECTED20
add wave -noupdate /tb/dut/control/UNCONNECTED21
add wave -noupdate /tb/dut/control/UNCONNECTED22
add wave -noupdate /tb/dut/control/UNCONNECTED23
add wave -noupdate /tb/dut/control/UNCONNECTED24
add wave -noupdate /tb/dut/control/UNCONNECTED25
add wave -noupdate /tb/dut/control/UNCONNECTED26
add wave -noupdate /tb/dut/control/UNCONNECTED27
add wave -noupdate /tb/dut/control/UNCONNECTED28
add wave -noupdate /tb/dut/control/UNCONNECTED29
add wave -noupdate /tb/dut/control/UNCONNECTED30
add wave -noupdate /tb/dut/control/UNCONNECTED31
add wave -noupdate /tb/dut/control/UNCONNECTED32
add wave -noupdate /tb/dut/control/UNCONNECTED33
add wave -noupdate /tb/dut/control/UNCONNECTED34
add wave -noupdate /tb/dut/control/UNCONNECTED35
add wave -noupdate /tb/dut/control/UNCONNECTED36
add wave -noupdate /tb/dut/control/UNCONNECTED37
add wave -noupdate /tb/dut/control/UNCONNECTED38
add wave -noupdate /tb/dut/control/UNCONNECTED39
add wave -noupdate /tb/dut/control/UNCONNECTED40
add wave -noupdate /tb/dut/control/UNCONNECTED41
add wave -noupdate /tb/dut/control/UNCONNECTED42
add wave -noupdate /tb/dut/control/UNCONNECTED43
add wave -noupdate /tb/dut/control/UNCONNECTED44
add wave -noupdate /tb/dut/control/UNCONNECTED45
add wave -noupdate /tb/dut/control/UNCONNECTED46
add wave -noupdate /tb/dut/control/UNCONNECTED47
add wave -noupdate /tb/dut/control/UNCONNECTED48
add wave -noupdate /tb/dut/control/UNCONNECTED49
add wave -noupdate /tb/dut/control/UNCONNECTED50
add wave -noupdate /tb/dut/control/UNCONNECTED51
add wave -noupdate /tb/dut/control/UNCONNECTED52
add wave -noupdate /tb/dut/control/UNCONNECTED53
add wave -noupdate /tb/dut/control/UNCONNECTED54
add wave -noupdate /tb/dut/control/UNCONNECTED55
add wave -noupdate /tb/dut/control/UNCONNECTED56
add wave -noupdate /tb/dut/control/UNCONNECTED57
add wave -noupdate /tb/dut/control/UNCONNECTED58
add wave -noupdate /tb/dut/control/UNCONNECTED59
add wave -noupdate /tb/dut/control/n_0
add wave -noupdate /tb/dut/control/n_1
add wave -noupdate /tb/dut/control/n_2
add wave -noupdate /tb/dut/control/n_3
add wave -noupdate /tb/dut/control/n_4
add wave -noupdate /tb/dut/control/n_5
add wave -noupdate /tb/dut/control/n_6
add wave -noupdate /tb/dut/control/n_7
add wave -noupdate /tb/dut/control/n_8
add wave -noupdate /tb/dut/control/n_9
add wave -noupdate /tb/dut/control/n_10
add wave -noupdate /tb/dut/control/n_11
add wave -noupdate /tb/dut/control/n_12
add wave -noupdate /tb/dut/control/n_13
add wave -noupdate /tb/dut/control/n_14
add wave -noupdate /tb/dut/control/n_15
add wave -noupdate /tb/dut/control/n_16
add wave -noupdate /tb/dut/control/n_17
add wave -noupdate /tb/dut/control/n_18
add wave -noupdate /tb/dut/control/n_19
add wave -noupdate /tb/dut/control/n_20
add wave -noupdate /tb/dut/control/n_21
add wave -noupdate /tb/dut/control/n_22
add wave -noupdate /tb/dut/control/n_23
add wave -noupdate /tb/dut/control/n_24
add wave -noupdate /tb/dut/control/n_25
add wave -noupdate /tb/dut/control/n_26
add wave -noupdate /tb/dut/control/n_27
add wave -noupdate /tb/dut/control/n_28
add wave -noupdate /tb/dut/control/n_29
add wave -noupdate /tb/dut/control/n_30
add wave -noupdate /tb/dut/control/n_31
add wave -noupdate /tb/dut/control/n_32
add wave -noupdate /tb/dut/control/n_33
add wave -noupdate /tb/dut/control/n_34
add wave -noupdate /tb/dut/control/n_35
add wave -noupdate /tb/dut/control/n_36
add wave -noupdate /tb/dut/control/n_37
add wave -noupdate /tb/dut/control/n_38
add wave -noupdate /tb/dut/control/n_39
add wave -noupdate /tb/dut/control/n_40
add wave -noupdate /tb/dut/control/n_41
add wave -noupdate /tb/dut/control/n_42
add wave -noupdate /tb/dut/control/n_43
add wave -noupdate /tb/dut/control/n_44
add wave -noupdate /tb/dut/control/n_45
add wave -noupdate /tb/dut/control/n_46
add wave -noupdate /tb/dut/control/n_47
add wave -noupdate /tb/dut/control/n_48
add wave -noupdate /tb/dut/control/n_49
add wave -noupdate /tb/dut/control/n_50
add wave -noupdate /tb/dut/control/n_51
add wave -noupdate /tb/dut/control/n_52
add wave -noupdate /tb/dut/control/n_53
add wave -noupdate /tb/dut/control/n_54
add wave -noupdate /tb/dut/control/n_55
add wave -noupdate /tb/dut/control/n_56
add wave -noupdate /tb/dut/control/n_57
add wave -noupdate /tb/dut/control/n_58
add wave -noupdate /tb/dut/control/n_59
add wave -noupdate /tb/dut/control/n_60
add wave -noupdate /tb/dut/control/n_61
add wave -noupdate /tb/dut/control/n_62
add wave -noupdate /tb/dut/control/n_63
add wave -noupdate /tb/dut/control/n_64
add wave -noupdate /tb/dut/control/n_65
add wave -noupdate /tb/dut/control/n_66
add wave -noupdate /tb/dut/control/n_67
add wave -noupdate /tb/dut/control/n_68
add wave -noupdate /tb/dut/control/n_69
add wave -noupdate /tb/dut/control/n_70
add wave -noupdate /tb/dut/control/n_71
add wave -noupdate /tb/dut/control/n_72
add wave -noupdate /tb/dut/control/n_73
add wave -noupdate /tb/dut/control/n_74
add wave -noupdate /tb/dut/control/n_75
add wave -noupdate /tb/dut/control/n_76
add wave -noupdate /tb/dut/control/n_77
add wave -noupdate /tb/dut/control/n_78
add wave -noupdate /tb/dut/control/n_79
add wave -noupdate /tb/dut/control/n_80
add wave -noupdate /tb/dut/control/n_81
add wave -noupdate /tb/dut/control/n_82
add wave -noupdate /tb/dut/control/n_83
add wave -noupdate /tb/dut/control/n_84
add wave -noupdate /tb/dut/control/n_85
add wave -noupdate /tb/dut/control/n_86
add wave -noupdate /tb/dut/control/n_87
add wave -noupdate /tb/dut/control/n_88
add wave -noupdate /tb/dut/control/n_89
add wave -noupdate /tb/dut/control/n_90
add wave -noupdate /tb/dut/control/n_91
add wave -noupdate /tb/dut/control/n_92
add wave -noupdate /tb/dut/control/n_93
add wave -noupdate /tb/dut/control/n_94
add wave -noupdate /tb/dut/control/n_95
add wave -noupdate /tb/dut/control/n_96
add wave -noupdate /tb/dut/control/n_97
add wave -noupdate /tb/dut/control/n_98
add wave -noupdate /tb/dut/control/n_99
add wave -noupdate /tb/dut/control/n_100
add wave -noupdate /tb/dut/control/n_101
add wave -noupdate /tb/dut/control/n_102
add wave -noupdate /tb/dut/control/n_103
add wave -noupdate /tb/dut/control/n_104
add wave -noupdate /tb/dut/control/n_105
add wave -noupdate /tb/dut/control/n_106
add wave -noupdate /tb/dut/control/n_107
add wave -noupdate /tb/dut/control/n_108
add wave -noupdate /tb/dut/control/n_109
add wave -noupdate /tb/dut/control/n_110
add wave -noupdate /tb/dut/control/n_111
add wave -noupdate /tb/dut/control/n_112
add wave -noupdate /tb/dut/control/n_113
add wave -noupdate /tb/dut/control/n_114
add wave -noupdate /tb/dut/control/n_115
add wave -noupdate /tb/dut/control/n_116
add wave -noupdate /tb/dut/control/n_117
add wave -noupdate /tb/dut/control/n_118
add wave -noupdate /tb/dut/control/n_119
add wave -noupdate /tb/dut/control/n_120
add wave -noupdate /tb/dut/control/n_121
add wave -noupdate /tb/dut/control/n_122
add wave -noupdate /tb/dut/control/n_123
add wave -noupdate /tb/dut/control/n_124
add wave -noupdate /tb/dut/control/n_125
add wave -noupdate /tb/dut/control/n_126
add wave -noupdate /tb/dut/control/n_127
add wave -noupdate /tb/dut/control/n_128
add wave -noupdate /tb/dut/control/n_129
add wave -noupdate /tb/dut/control/n_130
add wave -noupdate /tb/dut/control/n_131
add wave -noupdate /tb/dut/control/n_132
add wave -noupdate /tb/dut/control/n_133
add wave -noupdate /tb/dut/control/n_134
add wave -noupdate /tb/dut/control/n_135
add wave -noupdate /tb/dut/control/n_136
add wave -noupdate /tb/dut/control/n_137
add wave -noupdate /tb/dut/control/n_138
add wave -noupdate /tb/dut/control/n_139
add wave -noupdate /tb/dut/control/n_140
add wave -noupdate /tb/dut/control/n_141
add wave -noupdate /tb/dut/control/n_142
add wave -noupdate /tb/dut/control/n_143
add wave -noupdate /tb/dut/control/n_144
add wave -noupdate /tb/dut/control/n_145
add wave -noupdate /tb/dut/control/n_146
add wave -noupdate /tb/dut/control/n_147
add wave -noupdate /tb/dut/control/n_148
add wave -noupdate /tb/dut/control/n_149
add wave -noupdate /tb/dut/control/n_150
add wave -noupdate /tb/dut/control/n_151
add wave -noupdate /tb/dut/control/n_152
add wave -noupdate /tb/dut/control/n_153
add wave -noupdate /tb/dut/control/n_154
add wave -noupdate /tb/dut/control/n_155
add wave -noupdate /tb/dut/control/n_156
add wave -noupdate /tb/dut/control/n_157
add wave -noupdate /tb/dut/control/n_158
add wave -noupdate /tb/dut/control/n_159
add wave -noupdate /tb/dut/control/n_160
add wave -noupdate /tb/dut/control/n_161
add wave -noupdate /tb/dut/control/n_162
add wave -noupdate /tb/dut/control/n_163
add wave -noupdate /tb/dut/control/n_164
add wave -noupdate /tb/dut/control/n_165
add wave -noupdate /tb/dut/control/n_166
add wave -noupdate /tb/dut/control/n_167
add wave -noupdate /tb/dut/control/n_168
add wave -noupdate /tb/dut/control/n_169
add wave -noupdate /tb/dut/control/n_170
add wave -noupdate /tb/dut/control/n_171
add wave -noupdate /tb/dut/control/n_172
add wave -noupdate /tb/dut/control/n_173
add wave -noupdate /tb/dut/control/n_174
add wave -noupdate /tb/dut/control/n_175
add wave -noupdate /tb/dut/control/n_176
add wave -noupdate /tb/dut/control/n_177
add wave -noupdate /tb/dut/control/n_178
add wave -noupdate /tb/dut/control/n_179
add wave -noupdate /tb/dut/control/n_180
add wave -noupdate /tb/dut/control/n_181
add wave -noupdate /tb/dut/control/n_182
add wave -noupdate /tb/dut/control/n_183
add wave -noupdate /tb/dut/control/n_184
add wave -noupdate /tb/dut/control/n_185
add wave -noupdate /tb/dut/control/n_186
add wave -noupdate /tb/dut/control/n_187
add wave -noupdate /tb/dut/control/n_188
add wave -noupdate /tb/dut/control/n_189
add wave -noupdate /tb/dut/control/n_190
add wave -noupdate /tb/dut/control/n_191
add wave -noupdate /tb/dut/control/n_192
add wave -noupdate /tb/dut/control/n_193
add wave -noupdate /tb/dut/control/n_197
add wave -noupdate /tb/dut/control/n_198
add wave -noupdate /tb/dut/control/n_199
add wave -noupdate /tb/dut/control/n_200
add wave -noupdate /tb/dut/control/n_201
add wave -noupdate /tb/dut/control/n_202
add wave -noupdate /tb/dut/control/n_203
add wave -noupdate /tb/dut/control/n_204
add wave -noupdate /tb/dut/control/n_205
add wave -noupdate /tb/dut/control/n_206
add wave -noupdate /tb/dut/control/n_207
add wave -noupdate /tb/dut/control/n_208
add wave -noupdate /tb/dut/control/n_210
add wave -noupdate /tb/dut/control/n_211
add wave -noupdate /tb/dut/control/n_212
add wave -noupdate /tb/dut/control/n_213
add wave -noupdate /tb/dut/control/n_214
add wave -noupdate /tb/dut/control/n_215
add wave -noupdate /tb/dut/control/n_217
add wave -noupdate /tb/dut/control/n_218
add wave -noupdate /tb/dut/control/n_219
add wave -noupdate /tb/dut/control/n_220
add wave -noupdate /tb/dut/control/n_221
add wave -noupdate /tb/dut/control/n_222
add wave -noupdate /tb/dut/control/n_223
add wave -noupdate /tb/dut/control/n_224
add wave -noupdate /tb/dut/control/n_225
add wave -noupdate /tb/dut/control/n_226
add wave -noupdate /tb/dut/control/n_227
add wave -noupdate /tb/dut/control/n_228
add wave -noupdate /tb/dut/control/n_229
add wave -noupdate /tb/dut/control/n_230
add wave -noupdate /tb/dut/control/n_231
add wave -noupdate /tb/dut/control/n_232
add wave -noupdate /tb/dut/control/n_233
add wave -noupdate /tb/dut/control/n_234
add wave -noupdate /tb/dut/control/n_235
add wave -noupdate /tb/dut/control/n_236
add wave -noupdate /tb/dut/control/n_237
add wave -noupdate /tb/dut/control/n_238
add wave -noupdate /tb/dut/control/n_239
add wave -noupdate /tb/dut/control/n_240
add wave -noupdate /tb/dut/control/n_241
add wave -noupdate /tb/dut/control/n_242
add wave -noupdate /tb/dut/control/n_243
add wave -noupdate /tb/dut/control/n_244
add wave -noupdate /tb/dut/control/n_245
add wave -noupdate /tb/dut/control/n_246
add wave -noupdate /tb/dut/control/n_247
add wave -noupdate /tb/dut/control/n_248
add wave -noupdate /tb/dut/control/n_249
add wave -noupdate /tb/dut/control/n_250
add wave -noupdate /tb/dut/control/n_251
add wave -noupdate /tb/dut/control/n_252
add wave -noupdate /tb/dut/control/n_253
add wave -noupdate /tb/dut/control/n_254
add wave -noupdate /tb/dut/control/n_255
add wave -noupdate /tb/dut/control/n_256
add wave -noupdate /tb/dut/control/n_257
add wave -noupdate /tb/dut/control/n_258
add wave -noupdate /tb/dut/control/n_259
add wave -noupdate /tb/dut/control/n_260
add wave -noupdate /tb/dut/control/n_261
add wave -noupdate /tb/dut/control/n_262
add wave -noupdate /tb/dut/control/n_263
add wave -noupdate /tb/dut/control/n_264
add wave -noupdate /tb/dut/control/n_265
add wave -noupdate /tb/dut/control/n_266
add wave -noupdate /tb/dut/control/n_267
add wave -noupdate /tb/dut/control/n_268
add wave -noupdate /tb/dut/control/n_269
add wave -noupdate /tb/dut/control/n_270
add wave -noupdate /tb/dut/control/n_271
add wave -noupdate /tb/dut/control/n_272
add wave -noupdate /tb/dut/control/n_273
add wave -noupdate /tb/dut/control/n_274
add wave -noupdate /tb/dut/control/n_275
add wave -noupdate /tb/dut/control/n_276
add wave -noupdate /tb/dut/control/n_277
add wave -noupdate /tb/dut/control/n_278
add wave -noupdate /tb/dut/control/n_279
add wave -noupdate /tb/dut/control/n_280
add wave -noupdate /tb/dut/control/n_281
add wave -noupdate /tb/dut/control/n_282
add wave -noupdate /tb/dut/control/n_283
add wave -noupdate /tb/dut/control/n_284
add wave -noupdate /tb/dut/control/n_285
add wave -noupdate /tb/dut/control/n_286
add wave -noupdate /tb/dut/control/n_287
add wave -noupdate /tb/dut/control/n_288
add wave -noupdate /tb/dut/control/n_289
add wave -noupdate /tb/dut/control/n_290
add wave -noupdate /tb/dut/control/n_291
add wave -noupdate /tb/dut/control/n_292
add wave -noupdate /tb/dut/control/n_293
add wave -noupdate /tb/dut/control/n_294
add wave -noupdate /tb/dut/control/n_295
add wave -noupdate /tb/dut/control/n_296
add wave -noupdate /tb/dut/control/n_297
add wave -noupdate /tb/dut/control/n_298
add wave -noupdate /tb/dut/control/n_299
add wave -noupdate /tb/dut/control/n_300
add wave -noupdate /tb/dut/control/n_301
add wave -noupdate /tb/dut/control/n_302
add wave -noupdate /tb/dut/control/n_303
add wave -noupdate /tb/dut/control/n_304
add wave -noupdate /tb/dut/control/n_305
add wave -noupdate /tb/dut/control/n_306
add wave -noupdate /tb/dut/control/n_307
add wave -noupdate /tb/dut/control/n_308
add wave -noupdate /tb/dut/control/n_309
add wave -noupdate /tb/dut/control/n_310
add wave -noupdate /tb/dut/control/n_311
add wave -noupdate /tb/dut/control/n_312
add wave -noupdate /tb/dut/control/n_313
add wave -noupdate /tb/dut/control/n_314
add wave -noupdate /tb/dut/control/n_315
add wave -noupdate /tb/dut/control/n_316
add wave -noupdate /tb/dut/control/n_317
add wave -noupdate /tb/dut/control/n_318
add wave -noupdate /tb/dut/control/n_319
add wave -noupdate /tb/dut/control/n_320
add wave -noupdate /tb/dut/control/n_321
add wave -noupdate /tb/dut/control/n_322
add wave -noupdate /tb/dut/control/n_323
add wave -noupdate /tb/dut/control/n_324
add wave -noupdate /tb/dut/control/n_325
add wave -noupdate /tb/dut/control/n_326
add wave -noupdate /tb/dut/control/n_327
add wave -noupdate /tb/dut/control/n_328
add wave -noupdate /tb/dut/control/n_329
add wave -noupdate /tb/dut/control/n_330
add wave -noupdate /tb/dut/control/n_331
add wave -noupdate /tb/dut/control/n_332
add wave -noupdate /tb/dut/control/n_333
add wave -noupdate /tb/dut/control/n_334
add wave -noupdate /tb/dut/control/n_335
add wave -noupdate /tb/dut/control/n_336
add wave -noupdate /tb/dut/control/n_337
add wave -noupdate /tb/dut/control/n_338
add wave -noupdate /tb/dut/control/n_339
add wave -noupdate /tb/dut/control/n_340
add wave -noupdate /tb/dut/control/n_341
add wave -noupdate /tb/dut/control/n_342
add wave -noupdate /tb/dut/control/n_343
add wave -noupdate /tb/dut/control/n_344
add wave -noupdate /tb/dut/control/n_347
add wave -noupdate /tb/dut/control/n_348
add wave -noupdate /tb/dut/control/n_349
add wave -noupdate /tb/dut/control/n_350
add wave -noupdate /tb/dut/control/n_351
add wave -noupdate /tb/dut/control/n_352
add wave -noupdate /tb/dut/control/n_353
add wave -noupdate /tb/dut/control/n_354
add wave -noupdate /tb/dut/control/n_355
add wave -noupdate /tb/dut/control/n_356
add wave -noupdate /tb/dut/control/n_357
add wave -noupdate /tb/dut/control/n_358
add wave -noupdate /tb/dut/control/n_359
add wave -noupdate /tb/dut/control/n_360
add wave -noupdate /tb/dut/control/n_361
add wave -noupdate /tb/dut/control/n_362
add wave -noupdate /tb/dut/control/n_363
add wave -noupdate /tb/dut/control/n_364
add wave -noupdate /tb/dut/control/n_365
add wave -noupdate /tb/dut/control/n_366
add wave -noupdate /tb/dut/control/n_367
add wave -noupdate /tb/dut/control/n_368
add wave -noupdate /tb/dut/control/n_369
add wave -noupdate /tb/dut/control/n_370
add wave -noupdate /tb/dut/control/n_371
add wave -noupdate /tb/dut/control/n_372
add wave -noupdate /tb/dut/control/n_373
add wave -noupdate /tb/dut/control/n_374
add wave -noupdate /tb/dut/control/n_375
add wave -noupdate /tb/dut/control/n_376
add wave -noupdate /tb/dut/control/n_377
add wave -noupdate /tb/dut/control/n_378
add wave -noupdate /tb/dut/control/n_379
add wave -noupdate /tb/dut/control/n_380
add wave -noupdate /tb/dut/control/n_381
add wave -noupdate /tb/dut/control/n_382
add wave -noupdate /tb/dut/control/n_383
add wave -noupdate /tb/dut/control/n_384
add wave -noupdate /tb/dut/control/n_385
add wave -noupdate /tb/dut/control/n_386
add wave -noupdate /tb/dut/control/n_387
add wave -noupdate /tb/dut/control/n_388
add wave -noupdate /tb/dut/control/n_389
add wave -noupdate /tb/dut/control/n_390
add wave -noupdate /tb/dut/control/n_391
add wave -noupdate /tb/dut/control/n_392
add wave -noupdate /tb/dut/control/n_393
add wave -noupdate /tb/dut/control/n_394
add wave -noupdate /tb/dut/control/n_395
add wave -noupdate /tb/dut/control/n_396
add wave -noupdate /tb/dut/control/n_397
add wave -noupdate /tb/dut/control/n_398
add wave -noupdate /tb/dut/control/n_399
add wave -noupdate /tb/dut/control/n_400
add wave -noupdate /tb/dut/control/n_401
add wave -noupdate /tb/dut/control/n_402
add wave -noupdate /tb/dut/control/n_403
add wave -noupdate /tb/dut/control/n_404
add wave -noupdate /tb/dut/control/n_405
add wave -noupdate /tb/dut/control/n_406
add wave -noupdate /tb/dut/control/n_407
add wave -noupdate /tb/dut/control/n_408
add wave -noupdate /tb/dut/control/n_409
add wave -noupdate /tb/dut/control/n_410
add wave -noupdate /tb/dut/control/n_411
add wave -noupdate /tb/dut/control/n_412
add wave -noupdate /tb/dut/control/n_413
add wave -noupdate /tb/dut/control/n_414
add wave -noupdate /tb/dut/control/n_415
add wave -noupdate /tb/dut/control/n_416
add wave -noupdate /tb/dut/control/n_417
add wave -noupdate /tb/dut/control/n_418
add wave -noupdate /tb/dut/control/n_419
add wave -noupdate /tb/dut/control/n_420
add wave -noupdate /tb/dut/control/n_421
add wave -noupdate /tb/dut/control/n_422
add wave -noupdate /tb/dut/control/n_423
add wave -noupdate /tb/dut/control/n_424
add wave -noupdate /tb/dut/control/n_425
add wave -noupdate /tb/dut/control/n_426
add wave -noupdate /tb/dut/control/n_427
add wave -noupdate /tb/dut/control/n_428
add wave -noupdate /tb/dut/control/n_429
add wave -noupdate /tb/dut/control/n_430
add wave -noupdate /tb/dut/control/n_431
add wave -noupdate /tb/dut/control/n_432
add wave -noupdate /tb/dut/control/n_433
add wave -noupdate /tb/dut/control/n_434
add wave -noupdate /tb/dut/control/n_435
add wave -noupdate /tb/dut/control/n_436
add wave -noupdate /tb/dut/control/n_437
add wave -noupdate /tb/dut/control/n_438
add wave -noupdate /tb/dut/control/n_439
add wave -noupdate /tb/dut/control/n_440
add wave -noupdate /tb/dut/control/n_441
add wave -noupdate /tb/dut/control/n_442
add wave -noupdate /tb/dut/control/n_443
add wave -noupdate /tb/dut/control/n_444
add wave -noupdate /tb/dut/control/n_445
add wave -noupdate /tb/dut/control/n_446
add wave -noupdate /tb/dut/control/n_447
add wave -noupdate /tb/dut/control/n_448
add wave -noupdate /tb/dut/control/n_449
add wave -noupdate /tb/dut/control/n_450
add wave -noupdate /tb/dut/control/n_451
add wave -noupdate /tb/dut/control/n_452
add wave -noupdate /tb/dut/control/n_453
add wave -noupdate /tb/dut/control/n_454
add wave -noupdate /tb/dut/control/n_455
add wave -noupdate /tb/dut/control/n_456
add wave -noupdate /tb/dut/control/n_457
add wave -noupdate /tb/dut/control/n_458
add wave -noupdate /tb/dut/control/n_459
add wave -noupdate /tb/dut/control/n_460
add wave -noupdate /tb/dut/control/n_461
add wave -noupdate /tb/dut/control/n_462
add wave -noupdate /tb/dut/control/n_463
add wave -noupdate /tb/dut/control/n_464
add wave -noupdate /tb/dut/control/n_465
add wave -noupdate /tb/dut/control/n_466
add wave -noupdate /tb/dut/control/n_467
add wave -noupdate /tb/dut/control/n_468
add wave -noupdate /tb/dut/control/n_469
add wave -noupdate /tb/dut/control/n_470
add wave -noupdate /tb/dut/control/n_471
add wave -noupdate /tb/dut/control/n_472
add wave -noupdate /tb/dut/control/n_473
add wave -noupdate /tb/dut/control/n_474
add wave -noupdate /tb/dut/control/n_475
add wave -noupdate /tb/dut/control/n_476
add wave -noupdate /tb/dut/control/n_477
add wave -noupdate /tb/dut/control/n_478
add wave -noupdate /tb/dut/control/n_479
add wave -noupdate /tb/dut/control/n_480
add wave -noupdate /tb/dut/control/n_481
add wave -noupdate /tb/dut/control/n_482
add wave -noupdate /tb/dut/control/n_483
add wave -noupdate /tb/dut/control/n_484
add wave -noupdate /tb/dut/control/n_485
add wave -noupdate /tb/dut/control/n_486
add wave -noupdate /tb/dut/control/n_487
add wave -noupdate /tb/dut/control/n_488
add wave -noupdate /tb/dut/control/n_489
add wave -noupdate /tb/dut/control/n_490
add wave -noupdate /tb/dut/control/n_491
add wave -noupdate /tb/dut/control/n_492
add wave -noupdate /tb/dut/control/n_493
add wave -noupdate /tb/dut/control/n_494
add wave -noupdate /tb/dut/control/n_495
add wave -noupdate /tb/dut/control/n_496
add wave -noupdate /tb/dut/control/n_497
add wave -noupdate /tb/dut/control/n_498
add wave -noupdate /tb/dut/control/n_499
add wave -noupdate /tb/dut/control/n_500
add wave -noupdate /tb/dut/control/n_501
add wave -noupdate /tb/dut/control/n_502
add wave -noupdate /tb/dut/control/n_503
add wave -noupdate /tb/dut/control/n_504
add wave -noupdate /tb/dut/control/n_505
add wave -noupdate /tb/dut/control/n_506
add wave -noupdate /tb/dut/control/n_507
add wave -noupdate /tb/dut/control/n_508
add wave -noupdate /tb/dut/control/n_509
add wave -noupdate /tb/dut/control/n_510
add wave -noupdate /tb/dut/control/n_511
add wave -noupdate /tb/dut/control/n_512
add wave -noupdate /tb/dut/control/n_513
add wave -noupdate /tb/dut/control/n_514
add wave -noupdate /tb/dut/control/n_515
add wave -noupdate /tb/dut/control/n_516
add wave -noupdate /tb/dut/control/n_517
add wave -noupdate /tb/dut/control/n_518
add wave -noupdate /tb/dut/control/n_519
add wave -noupdate /tb/dut/control/n_520
add wave -noupdate /tb/dut/control/n_521
add wave -noupdate /tb/dut/control/n_522
add wave -noupdate /tb/dut/control/n_523
add wave -noupdate /tb/dut/control/n_524
add wave -noupdate /tb/dut/control/n_525
add wave -noupdate /tb/dut/control/n_526
add wave -noupdate /tb/dut/control/n_527
add wave -noupdate /tb/dut/control/n_528
add wave -noupdate /tb/dut/control/n_529
add wave -noupdate /tb/dut/control/n_530
add wave -noupdate /tb/dut/control/n_531
add wave -noupdate /tb/dut/control/n_532
add wave -noupdate /tb/dut/control/n_533
add wave -noupdate /tb/dut/control/n_534
add wave -noupdate /tb/dut/control/n_535
add wave -noupdate /tb/dut/control/n_536
add wave -noupdate /tb/dut/control/n_537
add wave -noupdate /tb/dut/control/n_538
add wave -noupdate /tb/dut/control/n_539
add wave -noupdate /tb/dut/control/n_540
add wave -noupdate /tb/dut/control/n_541
add wave -noupdate /tb/dut/control/n_542
add wave -noupdate /tb/dut/control/n_543
add wave -noupdate /tb/dut/control/n_544
add wave -noupdate /tb/dut/control/n_545
add wave -noupdate /tb/dut/control/n_546
add wave -noupdate /tb/dut/control/n_547
add wave -noupdate /tb/dut/control/n_548
add wave -noupdate /tb/dut/control/n_549
add wave -noupdate /tb/dut/control/n_550
add wave -noupdate /tb/dut/control/n_551
add wave -noupdate /tb/dut/control/n_552
add wave -noupdate /tb/dut/control/n_553
add wave -noupdate /tb/dut/control/n_554
add wave -noupdate /tb/dut/control/n_555
add wave -noupdate /tb/dut/control/n_556
add wave -noupdate /tb/dut/control/n_557
add wave -noupdate /tb/dut/control/n_558
add wave -noupdate /tb/dut/control/n_559
add wave -noupdate /tb/dut/control/n_560
add wave -noupdate /tb/dut/control/n_561
add wave -noupdate /tb/dut/control/n_562
add wave -noupdate /tb/dut/control/n_563
add wave -noupdate /tb/dut/control/n_564
add wave -noupdate /tb/dut/control/n_565
add wave -noupdate /tb/dut/control/n_566
add wave -noupdate /tb/dut/control/n_567
add wave -noupdate /tb/dut/control/n_568
add wave -noupdate /tb/dut/control/n_569
add wave -noupdate /tb/dut/control/n_570
add wave -noupdate /tb/dut/control/n_571
add wave -noupdate /tb/dut/control/n_572
add wave -noupdate /tb/dut/control/n_573
add wave -noupdate /tb/dut/control/n_574
add wave -noupdate /tb/dut/control/n_575
add wave -noupdate /tb/dut/control/n_576
add wave -noupdate /tb/dut/control/n_577
add wave -noupdate /tb/dut/control/n_578
add wave -noupdate /tb/dut/control/n_579
add wave -noupdate /tb/dut/control/n_580
add wave -noupdate /tb/dut/control/n_581
add wave -noupdate /tb/dut/control/n_582
add wave -noupdate /tb/dut/control/n_583
add wave -noupdate /tb/dut/control/n_584
add wave -noupdate /tb/dut/control/n_585
add wave -noupdate /tb/dut/control/n_586
add wave -noupdate /tb/dut/control/n_587
add wave -noupdate /tb/dut/control/n_588
add wave -noupdate /tb/dut/control/n_589
add wave -noupdate /tb/dut/control/n_590
add wave -noupdate /tb/dut/control/n_591
add wave -noupdate /tb/dut/control/n_592
add wave -noupdate /tb/dut/control/n_593
add wave -noupdate /tb/dut/control/n_594
add wave -noupdate /tb/dut/control/n_595
add wave -noupdate /tb/dut/control/n_596
add wave -noupdate /tb/dut/control/n_597
add wave -noupdate /tb/dut/control/n_598
add wave -noupdate /tb/dut/control/n_599
add wave -noupdate /tb/dut/control/n_600
add wave -noupdate /tb/dut/control/n_601
add wave -noupdate /tb/dut/control/n_602
add wave -noupdate /tb/dut/control/n_603
add wave -noupdate /tb/dut/control/n_604
add wave -noupdate /tb/dut/control/n_605
add wave -noupdate /tb/dut/control/n_606
add wave -noupdate /tb/dut/control/n_607
add wave -noupdate /tb/dut/control/n_608
add wave -noupdate /tb/dut/control/n_609
add wave -noupdate /tb/dut/control/n_610
add wave -noupdate /tb/dut/control/n_611
add wave -noupdate /tb/dut/control/n_612
add wave -noupdate /tb/dut/control/n_613
add wave -noupdate /tb/dut/control/n_614
add wave -noupdate /tb/dut/control/n_615
add wave -noupdate /tb/dut/control/n_616
add wave -noupdate /tb/dut/control/n_617
add wave -noupdate /tb/dut/control/n_618
add wave -noupdate /tb/dut/control/n_619
add wave -noupdate /tb/dut/control/n_620
add wave -noupdate /tb/dut/control/n_621
add wave -noupdate /tb/dut/control/n_622
add wave -noupdate /tb/dut/control/n_623
add wave -noupdate /tb/dut/control/n_624
add wave -noupdate /tb/dut/control/n_625
add wave -noupdate /tb/dut/control/n_626
add wave -noupdate /tb/dut/control/n_627
add wave -noupdate /tb/dut/control/n_628
add wave -noupdate /tb/dut/control/n_629
add wave -noupdate /tb/dut/control/n_630
add wave -noupdate /tb/dut/control/n_631
add wave -noupdate /tb/dut/control/n_632
add wave -noupdate /tb/dut/control/n_633
add wave -noupdate /tb/dut/control/n_634
add wave -noupdate /tb/dut/control/n_635
add wave -noupdate /tb/dut/control/n_636
add wave -noupdate /tb/dut/control/n_637
add wave -noupdate /tb/dut/control/n_638
add wave -noupdate /tb/dut/control/n_639
add wave -noupdate /tb/dut/control/n_640
add wave -noupdate /tb/dut/control/n_641
add wave -noupdate /tb/dut/control/n_642
add wave -noupdate /tb/dut/control/n_643
add wave -noupdate /tb/dut/control/n_644
add wave -noupdate /tb/dut/control/n_645
add wave -noupdate /tb/dut/control/n_646
add wave -noupdate /tb/dut/control/n_647
add wave -noupdate /tb/dut/control/n_648
add wave -noupdate /tb/dut/control/n_649
add wave -noupdate /tb/dut/control/n_650
add wave -noupdate /tb/dut/control/n_651
add wave -noupdate /tb/dut/control/n_652
add wave -noupdate /tb/dut/control/n_653
add wave -noupdate /tb/dut/control/n_654
add wave -noupdate /tb/dut/control/n_655
add wave -noupdate /tb/dut/control/n_656
add wave -noupdate /tb/dut/control/n_657
add wave -noupdate /tb/dut/control/n_658
add wave -noupdate /tb/dut/control/n_659
add wave -noupdate /tb/dut/control/n_660
add wave -noupdate /tb/dut/control/n_661
add wave -noupdate /tb/dut/control/n_662
add wave -noupdate /tb/dut/control/n_663
add wave -noupdate /tb/dut/control/n_664
add wave -noupdate /tb/dut/control/n_665
add wave -noupdate /tb/dut/control/n_666
add wave -noupdate /tb/dut/control/n_667
add wave -noupdate /tb/dut/control/n_668
add wave -noupdate /tb/dut/control/n_669
add wave -noupdate /tb/dut/control/n_670
add wave -noupdate /tb/dut/control/n_671
add wave -noupdate /tb/dut/control/n_672
add wave -noupdate /tb/dut/control/n_673
add wave -noupdate /tb/dut/control/n_674
add wave -noupdate /tb/dut/control/n_675
add wave -noupdate /tb/dut/control/n_676
add wave -noupdate /tb/dut/control/n_677
add wave -noupdate /tb/dut/control/n_678
add wave -noupdate /tb/dut/control/n_679
add wave -noupdate /tb/dut/control/n_680
add wave -noupdate /tb/dut/control/n_681
add wave -noupdate /tb/dut/control/n_682
add wave -noupdate /tb/dut/control/n_683
add wave -noupdate /tb/dut/control/n_684
add wave -noupdate /tb/dut/control/n_685
add wave -noupdate /tb/dut/control/n_686
add wave -noupdate /tb/dut/control/n_687
add wave -noupdate /tb/dut/control/n_688
add wave -noupdate /tb/dut/control/n_689
add wave -noupdate /tb/dut/control/n_690
add wave -noupdate /tb/dut/control/n_691
add wave -noupdate /tb/dut/control/n_692
add wave -noupdate /tb/dut/control/n_693
add wave -noupdate /tb/dut/control/n_694
add wave -noupdate /tb/dut/control/n_695
add wave -noupdate /tb/dut/control/n_696
add wave -noupdate /tb/dut/control/n_697
add wave -noupdate /tb/dut/control/n_698
add wave -noupdate /tb/dut/control/n_699
add wave -noupdate /tb/dut/control/n_700
add wave -noupdate /tb/dut/control/n_701
add wave -noupdate /tb/dut/control/n_702
add wave -noupdate /tb/dut/control/n_703
add wave -noupdate /tb/dut/control/n_704
add wave -noupdate /tb/dut/control/n_705
add wave -noupdate /tb/dut/control/n_706
add wave -noupdate /tb/dut/control/n_707
add wave -noupdate /tb/dut/control/n_708
add wave -noupdate /tb/dut/control/n_709
add wave -noupdate /tb/dut/control/n_710
add wave -noupdate /tb/dut/control/n_711
add wave -noupdate /tb/dut/control/n_712
add wave -noupdate /tb/dut/control/n_713
add wave -noupdate /tb/dut/control/n_714
add wave -noupdate /tb/dut/control/n_715
add wave -noupdate /tb/dut/control/n_716
add wave -noupdate /tb/dut/control/n_717
add wave -noupdate /tb/dut/control/n_718
add wave -noupdate /tb/dut/control/n_719
add wave -noupdate /tb/dut/control/n_720
add wave -noupdate /tb/dut/control/n_721
add wave -noupdate /tb/dut/control/n_722
add wave -noupdate /tb/dut/control/n_723
add wave -noupdate /tb/dut/control/n_724
add wave -noupdate /tb/dut/control/n_725
add wave -noupdate /tb/dut/control/n_726
add wave -noupdate /tb/dut/control/n_727
add wave -noupdate /tb/dut/control/n_728
add wave -noupdate /tb/dut/control/n_729
add wave -noupdate /tb/dut/control/n_730
add wave -noupdate /tb/dut/control/n_731
add wave -noupdate /tb/dut/control/n_732
add wave -noupdate /tb/dut/control/n_733
add wave -noupdate /tb/dut/control/n_734
add wave -noupdate /tb/dut/control/n_735
add wave -noupdate /tb/dut/control/n_736
add wave -noupdate /tb/dut/control/n_737
add wave -noupdate /tb/dut/control/n_738
add wave -noupdate /tb/dut/control/n_739
add wave -noupdate /tb/dut/control/n_740
add wave -noupdate /tb/dut/control/n_741
add wave -noupdate /tb/dut/control/n_742
add wave -noupdate /tb/dut/control/n_743
add wave -noupdate /tb/dut/control/n_744
add wave -noupdate /tb/dut/control/n_745
add wave -noupdate /tb/dut/control/n_746
add wave -noupdate /tb/dut/control/n_747
add wave -noupdate /tb/dut/control/n_748
add wave -noupdate /tb/dut/control/n_749
add wave -noupdate /tb/dut/control/n_750
add wave -noupdate /tb/dut/control/n_751
add wave -noupdate /tb/dut/control/n_752
add wave -noupdate /tb/dut/control/n_753
add wave -noupdate /tb/dut/control/n_754
add wave -noupdate /tb/dut/control/n_755
add wave -noupdate /tb/dut/control/n_756
add wave -noupdate /tb/dut/control/n_757
add wave -noupdate /tb/dut/control/n_758
add wave -noupdate /tb/dut/control/n_759
add wave -noupdate /tb/dut/control/n_760
add wave -noupdate /tb/dut/control/n_761
add wave -noupdate /tb/dut/control/n_762
add wave -noupdate /tb/dut/control/n_763
add wave -noupdate /tb/dut/control/n_764
add wave -noupdate /tb/dut/control/n_765
add wave -noupdate /tb/dut/control/n_766
add wave -noupdate /tb/dut/control/n_767
add wave -noupdate /tb/dut/control/n_768
add wave -noupdate /tb/dut/control/n_769
add wave -noupdate /tb/dut/control/n_770
add wave -noupdate /tb/dut/control/n_771
add wave -noupdate /tb/dut/control/n_772
add wave -noupdate /tb/dut/control/n_773
add wave -noupdate /tb/dut/control/n_774
add wave -noupdate /tb/dut/control/n_775
add wave -noupdate /tb/dut/control/n_776
add wave -noupdate /tb/dut/control/n_777
add wave -noupdate /tb/dut/control/n_778
add wave -noupdate /tb/dut/control/n_779
add wave -noupdate /tb/dut/control/n_780
add wave -noupdate /tb/dut/control/n_781
add wave -noupdate /tb/dut/control/n_782
add wave -noupdate /tb/dut/control/n_783
add wave -noupdate /tb/dut/control/n_784
add wave -noupdate /tb/dut/control/n_785
add wave -noupdate /tb/dut/control/n_786
add wave -noupdate /tb/dut/control/n_787
add wave -noupdate /tb/dut/control/n_788
add wave -noupdate /tb/dut/control/n_789
add wave -noupdate /tb/dut/control/n_790
add wave -noupdate /tb/dut/control/n_791
add wave -noupdate /tb/dut/control/n_792
add wave -noupdate /tb/dut/control/n_793
add wave -noupdate /tb/dut/control/n_794
add wave -noupdate /tb/dut/control/n_795
add wave -noupdate /tb/dut/control/n_796
add wave -noupdate /tb/dut/control/n_797
add wave -noupdate /tb/dut/control/n_798
add wave -noupdate /tb/dut/control/n_799
add wave -noupdate /tb/dut/control/n_800
add wave -noupdate /tb/dut/control/n_801
add wave -noupdate /tb/dut/control/n_802
add wave -noupdate /tb/dut/control/n_803
add wave -noupdate /tb/dut/control/n_804
add wave -noupdate /tb/dut/control/n_805
add wave -noupdate /tb/dut/control/n_806
add wave -noupdate /tb/dut/control/n_807
add wave -noupdate /tb/dut/control/n_808
add wave -noupdate /tb/dut/control/n_809
add wave -noupdate /tb/dut/control/n_810
add wave -noupdate /tb/dut/control/n_811
add wave -noupdate /tb/dut/control/n_812
add wave -noupdate /tb/dut/control/n_813
add wave -noupdate /tb/dut/control/n_814
add wave -noupdate /tb/dut/control/n_815
add wave -noupdate /tb/dut/control/n_816
add wave -noupdate /tb/dut/control/n_817
add wave -noupdate /tb/dut/control/n_818
add wave -noupdate /tb/dut/control/n_819
add wave -noupdate /tb/dut/control/n_820
add wave -noupdate /tb/dut/control/n_821
add wave -noupdate /tb/dut/control/n_822
add wave -noupdate /tb/dut/control/n_823
add wave -noupdate /tb/dut/control/n_824
add wave -noupdate /tb/dut/control/n_825
add wave -noupdate /tb/dut/control/n_826
add wave -noupdate /tb/dut/control/n_827
add wave -noupdate /tb/dut/control/n_828
add wave -noupdate /tb/dut/control/n_829
add wave -noupdate /tb/dut/control/n_830
add wave -noupdate /tb/dut/control/n_831
add wave -noupdate /tb/dut/control/n_832
add wave -noupdate /tb/dut/control/n_833
add wave -noupdate /tb/dut/control/n_834
add wave -noupdate /tb/dut/control/n_835
add wave -noupdate /tb/dut/control/n_836
add wave -noupdate /tb/dut/control/n_837
add wave -noupdate /tb/dut/control/n_838
add wave -noupdate /tb/dut/control/n_839
add wave -noupdate /tb/dut/control/n_840
add wave -noupdate /tb/dut/control/n_841
add wave -noupdate /tb/dut/control/n_842
add wave -noupdate /tb/dut/control/n_843
add wave -noupdate /tb/dut/control/n_844
add wave -noupdate /tb/dut/control/n_845
add wave -noupdate /tb/dut/control/n_846
add wave -noupdate /tb/dut/control/n_847
add wave -noupdate /tb/dut/control/n_848
add wave -noupdate /tb/dut/control/n_849
add wave -noupdate /tb/dut/control/n_850
add wave -noupdate /tb/dut/control/n_851
add wave -noupdate /tb/dut/control/n_852
add wave -noupdate /tb/dut/control/n_853
add wave -noupdate /tb/dut/control/n_854
add wave -noupdate /tb/dut/control/n_855
add wave -noupdate /tb/dut/control/n_856
add wave -noupdate /tb/dut/control/n_857
add wave -noupdate /tb/dut/control/n_858
add wave -noupdate /tb/dut/control/n_859
add wave -noupdate /tb/dut/control/n_860
add wave -noupdate /tb/dut/control/n_861
add wave -noupdate /tb/dut/control/n_862
add wave -noupdate /tb/dut/control/n_863
add wave -noupdate /tb/dut/control/n_864
add wave -noupdate /tb/dut/control/n_865
add wave -noupdate /tb/dut/control/n_866
add wave -noupdate /tb/dut/control/n_867
add wave -noupdate /tb/dut/control/n_868
add wave -noupdate /tb/dut/control/n_869
add wave -noupdate /tb/dut/control/n_870
add wave -noupdate /tb/dut/control/n_871
add wave -noupdate /tb/dut/control/n_872
add wave -noupdate /tb/dut/control/n_873
add wave -noupdate /tb/dut/control/n_874
add wave -noupdate /tb/dut/control/n_875
add wave -noupdate /tb/dut/control/n_876
add wave -noupdate /tb/dut/control/n_877
add wave -noupdate /tb/dut/control/n_878
add wave -noupdate /tb/dut/control/n_879
add wave -noupdate /tb/dut/control/n_880
add wave -noupdate /tb/dut/control/n_881
add wave -noupdate /tb/dut/control/n_882
add wave -noupdate /tb/dut/control/n_883
add wave -noupdate /tb/dut/control/n_884
add wave -noupdate /tb/dut/control/n_885
add wave -noupdate /tb/dut/control/n_886
add wave -noupdate /tb/dut/control/n_887
add wave -noupdate /tb/dut/control/n_888
add wave -noupdate /tb/dut/control/n_889
add wave -noupdate /tb/dut/control/n_890
add wave -noupdate /tb/dut/control/n_891
add wave -noupdate /tb/dut/control/n_892
add wave -noupdate /tb/dut/control/n_893
add wave -noupdate /tb/dut/control/n_894
add wave -noupdate /tb/dut/control/n_895
add wave -noupdate /tb/dut/control/n_896
add wave -noupdate /tb/dut/control/n_897
add wave -noupdate /tb/dut/control/n_898
add wave -noupdate /tb/dut/control/n_899
add wave -noupdate /tb/dut/control/n_900
add wave -noupdate /tb/dut/control/n_901
add wave -noupdate /tb/dut/control/n_902
add wave -noupdate /tb/dut/control/n_903
add wave -noupdate /tb/dut/control/n_904
add wave -noupdate /tb/dut/control/n_905
add wave -noupdate /tb/dut/control/n_906
add wave -noupdate /tb/dut/control/n_907
add wave -noupdate /tb/dut/control/n_908
add wave -noupdate /tb/dut/control/n_909
add wave -noupdate /tb/dut/control/n_910
add wave -noupdate /tb/dut/control/n_911
add wave -noupdate /tb/dut/control/n_912
add wave -noupdate /tb/dut/control/n_913
add wave -noupdate /tb/dut/control/n_914
add wave -noupdate /tb/dut/control/n_915
add wave -noupdate /tb/dut/control/n_916
add wave -noupdate /tb/dut/control/n_917
add wave -noupdate /tb/dut/control/n_918
add wave -noupdate /tb/dut/control/n_919
add wave -noupdate /tb/dut/control/n_920
add wave -noupdate /tb/dut/control/n_921
add wave -noupdate /tb/dut/control/n_922
add wave -noupdate /tb/dut/control/n_923
add wave -noupdate /tb/dut/control/n_924
add wave -noupdate /tb/dut/control/n_925
add wave -noupdate /tb/dut/control/n_926
add wave -noupdate /tb/dut/control/n_927
add wave -noupdate /tb/dut/control/n_928
add wave -noupdate /tb/dut/control/n_929
add wave -noupdate /tb/dut/control/n_930
add wave -noupdate /tb/dut/control/n_931
add wave -noupdate /tb/dut/control/n_932
add wave -noupdate /tb/dut/control/n_933
add wave -noupdate /tb/dut/control/n_934
add wave -noupdate /tb/dut/control/n_935
add wave -noupdate /tb/dut/control/n_936
add wave -noupdate /tb/dut/control/n_937
add wave -noupdate /tb/dut/control/n_938
add wave -noupdate /tb/dut/control/n_939
add wave -noupdate /tb/dut/control/n_940
add wave -noupdate /tb/dut/control/n_941
add wave -noupdate /tb/dut/control/n_942
add wave -noupdate /tb/dut/control/n_943
add wave -noupdate /tb/dut/control/n_944
add wave -noupdate /tb/dut/control/n_945
add wave -noupdate /tb/dut/control/n_946
add wave -noupdate /tb/dut/control/n_947
add wave -noupdate /tb/dut/control/n_948
add wave -noupdate /tb/dut/control/n_949
add wave -noupdate /tb/dut/control/n_950
add wave -noupdate /tb/dut/control/n_951
add wave -noupdate /tb/dut/control/n_952
add wave -noupdate /tb/dut/control/n_953
add wave -noupdate /tb/dut/control/n_954
add wave -noupdate /tb/dut/control/n_955
add wave -noupdate /tb/dut/control/n_956
add wave -noupdate /tb/dut/control/n_957
add wave -noupdate /tb/dut/control/n_958
add wave -noupdate /tb/dut/control/n_959
add wave -noupdate /tb/dut/control/n_960
add wave -noupdate /tb/dut/control/n_961
add wave -noupdate /tb/dut/control/n_962
add wave -noupdate /tb/dut/control/n_963
add wave -noupdate /tb/dut/control/n_964
add wave -noupdate /tb/dut/control/n_965
add wave -noupdate /tb/dut/control/n_966
add wave -noupdate /tb/dut/control/n_967
add wave -noupdate /tb/dut/control/n_968
add wave -noupdate /tb/dut/control/n_969
add wave -noupdate /tb/dut/control/n_970
add wave -noupdate /tb/dut/control/n_971
add wave -noupdate /tb/dut/control/n_972
add wave -noupdate /tb/dut/control/n_973
add wave -noupdate /tb/dut/control/n_974
add wave -noupdate /tb/dut/control/n_975
add wave -noupdate /tb/dut/control/n_976
add wave -noupdate /tb/dut/control/n_977
add wave -noupdate /tb/dut/control/n_978
add wave -noupdate /tb/dut/control/n_979
add wave -noupdate /tb/dut/control/n_980
add wave -noupdate /tb/dut/control/n_981
add wave -noupdate /tb/dut/control/n_982
add wave -noupdate /tb/dut/control/n_983
add wave -noupdate /tb/dut/control/n_984
add wave -noupdate /tb/dut/control/n_985
add wave -noupdate /tb/dut/control/n_986
add wave -noupdate /tb/dut/control/n_987
add wave -noupdate /tb/dut/control/n_988
add wave -noupdate /tb/dut/control/n_989
add wave -noupdate /tb/dut/control/n_990
add wave -noupdate /tb/dut/control/n_991
add wave -noupdate /tb/dut/control/n_992
add wave -noupdate /tb/dut/control/n_993
add wave -noupdate /tb/dut/control/n_994
add wave -noupdate /tb/dut/control/n_995
add wave -noupdate /tb/dut/control/n_996
add wave -noupdate /tb/dut/control/n_997
add wave -noupdate /tb/dut/control/n_998
add wave -noupdate /tb/dut/control/n_999
add wave -noupdate /tb/dut/control/n_1000
add wave -noupdate /tb/dut/control/n_1001
add wave -noupdate /tb/dut/control/n_1002
add wave -noupdate /tb/dut/control/n_1003
add wave -noupdate /tb/dut/control/n_1004
add wave -noupdate /tb/dut/control/n_1005
add wave -noupdate /tb/dut/control/n_1006
add wave -noupdate /tb/dut/control/n_1007
add wave -noupdate /tb/dut/control/n_1008
add wave -noupdate /tb/dut/control/n_1009
add wave -noupdate /tb/dut/control/n_1010
add wave -noupdate /tb/dut/control/n_1011
add wave -noupdate /tb/dut/control/n_1012
add wave -noupdate /tb/dut/control/n_1013
add wave -noupdate /tb/dut/control/n_1014
add wave -noupdate /tb/dut/control/n_1015
add wave -noupdate /tb/dut/control/n_1016
add wave -noupdate /tb/dut/control/n_1017
add wave -noupdate /tb/dut/control/n_1018
add wave -noupdate /tb/dut/control/n_1019
add wave -noupdate /tb/dut/control/n_1020
add wave -noupdate /tb/dut/control/n_1021
add wave -noupdate /tb/dut/control/n_1022
add wave -noupdate /tb/dut/control/n_1023
add wave -noupdate /tb/dut/control/n_1024
add wave -noupdate /tb/dut/control/n_1025
add wave -noupdate /tb/dut/control/n_1026
add wave -noupdate /tb/dut/control/n_1027
add wave -noupdate /tb/dut/control/n_1028
add wave -noupdate /tb/dut/control/n_1029
add wave -noupdate /tb/dut/control/n_1030
add wave -noupdate /tb/dut/control/n_1031
add wave -noupdate /tb/dut/control/n_1032
add wave -noupdate /tb/dut/control/n_1033
add wave -noupdate /tb/dut/control/n_1034
add wave -noupdate /tb/dut/control/n_1035
add wave -noupdate /tb/dut/control/n_1036
add wave -noupdate /tb/dut/control/n_1037
add wave -noupdate /tb/dut/control/n_1038
add wave -noupdate /tb/dut/control/n_1039
add wave -noupdate /tb/dut/control/n_1040
add wave -noupdate /tb/dut/control/n_1041
add wave -noupdate /tb/dut/control/n_1042
add wave -noupdate /tb/dut/control/n_1043
add wave -noupdate /tb/dut/control/n_1044
add wave -noupdate /tb/dut/control/n_1045
add wave -noupdate /tb/dut/control/n_1046
add wave -noupdate /tb/dut/control/n_1047
add wave -noupdate /tb/dut/control/n_1048
add wave -noupdate /tb/dut/control/n_1049
add wave -noupdate /tb/dut/control/n_1050
add wave -noupdate /tb/dut/control/n_1051
add wave -noupdate /tb/dut/control/n_1052
add wave -noupdate /tb/dut/control/n_1053
add wave -noupdate /tb/dut/control/n_1054
add wave -noupdate /tb/dut/control/n_1055
add wave -noupdate /tb/dut/control/n_1056
add wave -noupdate /tb/dut/control/n_1057
add wave -noupdate /tb/dut/control/n_1058
add wave -noupdate /tb/dut/control/n_1059
add wave -noupdate /tb/dut/control/n_1060
add wave -noupdate /tb/dut/control/n_1061
add wave -noupdate /tb/dut/control/n_1062
add wave -noupdate /tb/dut/control/n_1063
add wave -noupdate /tb/dut/control/n_1064
add wave -noupdate /tb/dut/control/n_1065
add wave -noupdate /tb/dut/control/n_1066
add wave -noupdate /tb/dut/control/n_1067
add wave -noupdate /tb/dut/control/n_1068
add wave -noupdate /tb/dut/control/n_1069
add wave -noupdate /tb/dut/control/n_1070
add wave -noupdate /tb/dut/control/n_1071
add wave -noupdate /tb/dut/control/n_1072
add wave -noupdate /tb/dut/control/n_1073
add wave -noupdate /tb/dut/control/n_1074
add wave -noupdate /tb/dut/control/n_1075
add wave -noupdate /tb/dut/control/n_1076
add wave -noupdate /tb/dut/control/n_1077
add wave -noupdate /tb/dut/control/n_1078
add wave -noupdate /tb/dut/control/n_1079
add wave -noupdate /tb/dut/control/n_1080
add wave -noupdate /tb/dut/control/n_1081
add wave -noupdate /tb/dut/control/n_1082
add wave -noupdate /tb/dut/control/n_1083
add wave -noupdate /tb/dut/control/n_1084
add wave -noupdate /tb/dut/control/n_1085
add wave -noupdate /tb/dut/control/n_1086
add wave -noupdate /tb/dut/control/n_1087
add wave -noupdate /tb/dut/control/n_1088
add wave -noupdate /tb/dut/control/n_1089
add wave -noupdate /tb/dut/control/n_1090
add wave -noupdate /tb/dut/control/n_1091
add wave -noupdate /tb/dut/control/n_1092
add wave -noupdate /tb/dut/control/n_1093
add wave -noupdate /tb/dut/control/n_1094
add wave -noupdate /tb/dut/control/n_1095
add wave -noupdate /tb/dut/control/n_1096
add wave -noupdate /tb/dut/control/n_1097
add wave -noupdate /tb/dut/control/n_1098
add wave -noupdate /tb/dut/control/n_1099
add wave -noupdate /tb/dut/control/n_1100
add wave -noupdate /tb/dut/control/n_1101
add wave -noupdate /tb/dut/control/n_1102
add wave -noupdate /tb/dut/control/n_1103
add wave -noupdate /tb/dut/control/n_1104
add wave -noupdate /tb/dut/control/n_1105
add wave -noupdate /tb/dut/control/n_1106
add wave -noupdate /tb/dut/control/n_1107
add wave -noupdate /tb/dut/control/n_1108
add wave -noupdate /tb/dut/control/n_1109
add wave -noupdate /tb/dut/control/n_1110
add wave -noupdate /tb/dut/control/n_1111
add wave -noupdate /tb/dut/control/n_1112
add wave -noupdate /tb/dut/control/n_1113
add wave -noupdate /tb/dut/control/n_1114
add wave -noupdate /tb/dut/control/n_1115
add wave -noupdate /tb/dut/control/n_1116
add wave -noupdate /tb/dut/control/n_1117
add wave -noupdate /tb/dut/control/n_1118
add wave -noupdate /tb/dut/control/n_1119
add wave -noupdate /tb/dut/control/n_1120
add wave -noupdate /tb/dut/control/n_1121
add wave -noupdate /tb/dut/control/n_1122
add wave -noupdate /tb/dut/control/n_1123
add wave -noupdate /tb/dut/control/n_1124
add wave -noupdate /tb/dut/control/n_1125
add wave -noupdate /tb/dut/control/n_1126
add wave -noupdate /tb/dut/control/n_1127
add wave -noupdate /tb/dut/control/n_1128
add wave -noupdate /tb/dut/control/n_1129
add wave -noupdate /tb/dut/control/n_1130
add wave -noupdate /tb/dut/control/n_1131
add wave -noupdate /tb/dut/control/n_1132
add wave -noupdate /tb/dut/control/n_1133
add wave -noupdate /tb/dut/control/n_1134
add wave -noupdate /tb/dut/control/n_1135
add wave -noupdate /tb/dut/control/n_1136
add wave -noupdate /tb/dut/control/n_1137
add wave -noupdate /tb/dut/control/n_1138
add wave -noupdate /tb/dut/control/n_1139
add wave -noupdate /tb/dut/control/n_1140
add wave -noupdate /tb/dut/control/n_1141
add wave -noupdate /tb/dut/control/n_1142
add wave -noupdate /tb/dut/control/n_1143
add wave -noupdate /tb/dut/control/n_1144
add wave -noupdate /tb/dut/control/n_1145
add wave -noupdate /tb/dut/control/n_1146
add wave -noupdate /tb/dut/control/n_1147
add wave -noupdate /tb/dut/control/n_1148
add wave -noupdate /tb/dut/control/n_1149
add wave -noupdate /tb/dut/control/n_1150
add wave -noupdate /tb/dut/control/n_1151
add wave -noupdate /tb/dut/control/n_1152
add wave -noupdate /tb/dut/control/n_1153
add wave -noupdate /tb/dut/control/n_1154
add wave -noupdate /tb/dut/control/n_1155
add wave -noupdate /tb/dut/control/n_1156
add wave -noupdate /tb/dut/control/n_1157
add wave -noupdate /tb/dut/control/n_1158
add wave -noupdate /tb/dut/control/n_1159
add wave -noupdate /tb/dut/control/n_1161
add wave -noupdate /tb/dut/control/n_1162
add wave -noupdate /tb/dut/control/n_1163
add wave -noupdate /tb/dut/control/n_1164
add wave -noupdate /tb/dut/control/n_1165
add wave -noupdate /tb/dut/control/n_1166
add wave -noupdate /tb/dut/control/n_1167
add wave -noupdate /tb/dut/control/n_1168
add wave -noupdate /tb/dut/control/n_1169
add wave -noupdate /tb/dut/control/n_1170
add wave -noupdate /tb/dut/control/n_1171
add wave -noupdate /tb/dut/control/n_1172
add wave -noupdate /tb/dut/control/n_1173
add wave -noupdate /tb/dut/control/n_1174
add wave -noupdate /tb/dut/control/n_1175
add wave -noupdate /tb/dut/control/n_1176
add wave -noupdate /tb/dut/control/n_1177
add wave -noupdate /tb/dut/control/n_1178
add wave -noupdate /tb/dut/control/n_1179
add wave -noupdate /tb/dut/control/n_1180
add wave -noupdate /tb/dut/control/n_1181
add wave -noupdate /tb/dut/control/n_1182
add wave -noupdate /tb/dut/control/n_1183
add wave -noupdate /tb/dut/control/n_1184
add wave -noupdate /tb/dut/control/n_1185
add wave -noupdate /tb/dut/control/n_1186
add wave -noupdate /tb/dut/control/n_1187
add wave -noupdate /tb/dut/control/n_1188
add wave -noupdate /tb/dut/control/n_1189
add wave -noupdate /tb/dut/control/n_1190
add wave -noupdate /tb/dut/control/n_1191
add wave -noupdate /tb/dut/control/n_1192
add wave -noupdate /tb/dut/control/n_1193
add wave -noupdate /tb/dut/control/n_1194
add wave -noupdate /tb/dut/control/n_1195
add wave -noupdate /tb/dut/control/n_1196
add wave -noupdate /tb/dut/control/n_1197
add wave -noupdate /tb/dut/control/n_1198
add wave -noupdate /tb/dut/control/n_1199
add wave -noupdate /tb/dut/control/n_1200
add wave -noupdate /tb/dut/control/n_1201
add wave -noupdate /tb/dut/control/n_1202
add wave -noupdate /tb/dut/control/n_1203
add wave -noupdate /tb/dut/control/n_1204
add wave -noupdate /tb/dut/control/n_1205
add wave -noupdate /tb/dut/control/n_1206
add wave -noupdate /tb/dut/control/n_1207
add wave -noupdate /tb/dut/control/n_1208
add wave -noupdate /tb/dut/control/n_1209
add wave -noupdate /tb/dut/control/n_1210
add wave -noupdate /tb/dut/control/n_1211
add wave -noupdate /tb/dut/control/n_1212
add wave -noupdate /tb/dut/control/n_1213
add wave -noupdate /tb/dut/control/n_1214
add wave -noupdate /tb/dut/control/n_1215
add wave -noupdate /tb/dut/control/n_1216
add wave -noupdate /tb/dut/control/n_1217
add wave -noupdate /tb/dut/control/n_1218
add wave -noupdate /tb/dut/control/n_1219
add wave -noupdate /tb/dut/control/n_1220
add wave -noupdate /tb/dut/control/n_1221
add wave -noupdate /tb/dut/control/n_1222
add wave -noupdate /tb/dut/control/n_1223
add wave -noupdate /tb/dut/control/n_1224
add wave -noupdate /tb/dut/control/n_1225
add wave -noupdate /tb/dut/control/n_1226
add wave -noupdate /tb/dut/control/n_1227
add wave -noupdate /tb/dut/control/n_1228
add wave -noupdate /tb/dut/control/n_1229
add wave -noupdate /tb/dut/control/n_1230
add wave -noupdate /tb/dut/control/n_1231
add wave -noupdate /tb/dut/control/n_1232
add wave -noupdate /tb/dut/control/n_1233
add wave -noupdate /tb/dut/control/n_1234
add wave -noupdate /tb/dut/control/n_1235
add wave -noupdate /tb/dut/control/n_1236
add wave -noupdate /tb/dut/control/n_1237
add wave -noupdate /tb/dut/control/n_1238
add wave -noupdate /tb/dut/control/n_1239
add wave -noupdate /tb/dut/control/n_1240
add wave -noupdate /tb/dut/control/n_1241
add wave -noupdate /tb/dut/control/n_1242
add wave -noupdate /tb/dut/control/n_1243
add wave -noupdate /tb/dut/control/n_1244
add wave -noupdate /tb/dut/control/n_1245
add wave -noupdate /tb/dut/control/n_1246
add wave -noupdate /tb/dut/control/n_1247
add wave -noupdate /tb/dut/control/n_1248
add wave -noupdate /tb/dut/control/n_1249
add wave -noupdate /tb/dut/control/n_1250
add wave -noupdate /tb/dut/control/n_1251
add wave -noupdate /tb/dut/control/n_1252
add wave -noupdate /tb/dut/control/n_1253
add wave -noupdate /tb/dut/control/n_1254
add wave -noupdate /tb/dut/control/n_1255
add wave -noupdate /tb/dut/control/n_1256
add wave -noupdate /tb/dut/control/n_1257
add wave -noupdate /tb/dut/control/n_1258
add wave -noupdate /tb/dut/control/n_1259
add wave -noupdate /tb/dut/control/n_1260
add wave -noupdate /tb/dut/control/n_1261
add wave -noupdate /tb/dut/control/n_1262
add wave -noupdate /tb/dut/control/n_1263
add wave -noupdate /tb/dut/control/n_1264
add wave -noupdate /tb/dut/control/n_1265
add wave -noupdate /tb/dut/control/n_1266
add wave -noupdate /tb/dut/control/n_1267
add wave -noupdate /tb/dut/control/n_1268
add wave -noupdate /tb/dut/control/n_1269
add wave -noupdate /tb/dut/control/n_1270
add wave -noupdate /tb/dut/control/n_1271
add wave -noupdate /tb/dut/control/n_1272
add wave -noupdate /tb/dut/control/n_1273
add wave -noupdate /tb/dut/control/n_1274
add wave -noupdate /tb/dut/control/n_1275
add wave -noupdate /tb/dut/control/n_1276
add wave -noupdate /tb/dut/control/n_1277
add wave -noupdate /tb/dut/control/n_1278
add wave -noupdate /tb/dut/control/n_1279
add wave -noupdate /tb/dut/control/n_1280
add wave -noupdate /tb/dut/control/n_1281
add wave -noupdate /tb/dut/control/n_1282
add wave -noupdate /tb/dut/control/n_1283
add wave -noupdate /tb/dut/control/n_1284
add wave -noupdate /tb/dut/control/n_1285
add wave -noupdate /tb/dut/control/n_1286
add wave -noupdate /tb/dut/control/n_1287
add wave -noupdate /tb/dut/control/n_1288
add wave -noupdate /tb/dut/control/n_1289
add wave -noupdate /tb/dut/control/n_1290
add wave -noupdate /tb/dut/control/n_1291
add wave -noupdate /tb/dut/control/n_1292
add wave -noupdate /tb/dut/control/n_1293
add wave -noupdate /tb/dut/control/n_1294
add wave -noupdate /tb/dut/control/n_1295
add wave -noupdate /tb/dut/control/n_1296
add wave -noupdate /tb/dut/control/n_1297
add wave -noupdate /tb/dut/control/n_1298
add wave -noupdate /tb/dut/control/n_1299
add wave -noupdate /tb/dut/control/n_1300
add wave -noupdate /tb/dut/control/n_1301
add wave -noupdate /tb/dut/control/n_1347
add wave -noupdate /tb/dut/control/r_fin_en
add wave -noupdate /tb/dut/control/r_wh_en
add wave -noupdate /tb/dut/control/rc_gclk
add wave -noupdate /tb/dut/control/rc_gclk_27955
add wave -noupdate /tb/dut/control/rc_gclk_27958
add wave -noupdate /tb/dut/control/rc_gclk_27961
add wave -noupdate /tb/dut/control/rc_gclk_27964
add wave -noupdate /tb/dut/control/rc_gclk_27967
add wave -noupdate /tb/dut/control/rc_gclk_27970
add wave -noupdate /tb/dut/control/rc_gclk_27973
add wave -noupdate /tb/dut/control/rc_gclk_27976
add wave -noupdate /tb/dut/control/rc_gclk_27979
add wave -noupdate /tb/dut/control/rc_gclk_27982
add wave -noupdate /tb/dut/control/rc_gclk_27985
add wave -noupdate /tb/dut/control/rc_gclk_27988
add wave -noupdate /tb/dut/control/rc_gclk_27991
add wave -noupdate /tb/dut/control/rc_gclk_27994
add wave -noupdate /tb/dut/control/rc_gclk_27997
add wave -noupdate /tb/dut/control/rc_gclk_28000
add wave -noupdate /tb/dut/control/rc_gclk_28003
add wave -noupdate /tb/dut/control/rc_gclk_28006
add wave -noupdate /tb/dut/control/rc_gclk_28009
add wave -noupdate /tb/dut/control/rc_gclk_28012
add wave -noupdate /tb/dut/control/rc_gclk_28015
add wave -noupdate /tb/dut/control/rc_gclk_28018
add wave -noupdate /tb/dut/control/rc_gclk_28021
add wave -noupdate /tb/dut/control/rc_gclk_28024
add wave -noupdate /tb/dut/control/rc_gclk_28027
add wave -noupdate /tb/dut/control/rc_gclk_28030
add wave -noupdate /tb/dut/control/rc_gclk_28033
add wave -noupdate /tb/dut/control/rc_gclk_28036
add wave -noupdate /tb/dut/control/rc_gclk_28039
add wave -noupdate /tb/dut/control/rc_gclk_28042
add wave -noupdate /tb/dut/control/rc_gclk_28045
add wave -noupdate /tb/dut/control/rc_gclk_28048
add wave -noupdate /tb/dut/control/rc_gclk_28051
add wave -noupdate /tb/dut/control/rc_gclk_28054
add wave -noupdate /tb/dut/control/rc_gclk_28057
add wave -noupdate /tb/dut/control/rc_gclk_28060
add wave -noupdate /tb/dut/control/rc_gclk_28063
add wave -noupdate /tb/dut/control/rc_gclk_28066
add wave -noupdate /tb/dut/control/rc_gclk_28069
add wave -noupdate /tb/dut/control/rc_gclk_28072
add wave -noupdate /tb/dut/control/rc_gclk_28075
add wave -noupdate /tb/dut/control/rc_gclk_28078
add wave -noupdate /tb/dut/control/rc_gclk_28081
add wave -noupdate /tb/dut/control/rc_gclk_28084
add wave -noupdate /tb/dut/control/rc_gclk_28087
add wave -noupdate /tb/dut/control/rc_gclk_28090
add wave -noupdate /tb/dut/control/rc_gclk_28093
add wave -noupdate /tb/dut/control/rc_gclk_28096
add wave -noupdate /tb/dut/control/rc_gclk_28099
add wave -noupdate /tb/dut/control/rc_gclk_28102
add wave -noupdate /tb/dut/control/rc_gclk_28105
add wave -noupdate /tb/dut/control/rc_gclk_28108
add wave -noupdate /tb/dut/control/rc_gclk_28111
add wave -noupdate /tb/dut/control/rc_gclk_28114
add wave -noupdate /tb/dut/control/rc_gclk_28117
add wave -noupdate /tb/dut/control/rc_gclk_28120
add wave -noupdate /tb/dut/control/rc_gclk_28123
add wave -noupdate /tb/dut/control/rc_gclk_28126
add wave -noupdate /tb/dut/control/rc_gclk_28129
add wave -noupdate /tb/dut/control/rc_gclk_28132
add wave -noupdate /tb/dut/control/rc_gclk_28135
add wave -noupdate /tb/dut/control/rc_gclk_28138
add wave -noupdate /tb/dut/control/rc_gclk_28141
add wave -noupdate /tb/dut/control/rc_gclk_28144
add wave -noupdate /tb/dut/control/rc_gclk_28147
add wave -noupdate /tb/dut/control/rc_gclk_28150
add wave -noupdate /tb/dut/control/rc_gclk_28153
add wave -noupdate /tb/dut/control/rc_gclk_28155
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {20088 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {19890 ns} {20675 ns}
