set CLK_PERIOD 2.0
set INPUT_SIZE 16
set DATAFLOW_TYPE ws
set ARRAY_TYPE syst2d
set LAT 2
set LAYER 3
set parameters {{N_FILTER 10} {N_CHANNEL 128} {STRIDE 1} {X_SIZE 3} {FILTER_WIDTH 1} {CONVS_PER_LINE 10} {MEM_SIZE 16} {INPUT_SIZE 16} {CARRY_SIZE 4} {SHIFT 8}}
