set CLK_PERIOD 1.0
set INPUT_SIZE 16
set DATAFLOW_TYPE ws
set ARRAY_TYPE syst2d
set LAT 2
set LAYER 1
set parameters {{N_FILTER 32} {N_CHANNEL 16} {STRIDE 2} {X_SIZE 15} {FILTER_WIDTH 3} {CONVS_PER_LINE 7} {MEM_SIZE 16} {INPUT_SIZE 16} {CARRY_SIZE 4} {SHIFT 8}}
